# Generated by Django 6.0.5 on 2026-05-19 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_alter_recipeingredient_recipe_profile_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
